# Generated by Django 4.2 on 2024-12-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0003_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='follow_up_required',
            field=models.BooleanField(default=False),
        ),
    ]
