# Generated by Django 4.2 on 2024-12-27 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0004_call_follow_up_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
