# Generated by Django 4.2 on 2024-12-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0005_call_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='call',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
