# Generated by Django 4.2 on 2024-12-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0006_remove_call_uuid_alter_call_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='call',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='call',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='call',
            name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='call',
            name='status',
        ),
    ]
