# Generated by Django 4.2 on 2024-12-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0008_call_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='call',
            name='purpose',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
