# Generated by Django 4.2 on 2024-12-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0009_alter_call_id_alter_call_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
